name: Build Landing Page
on:
  push:
    branches:
      - master
jobs:
  build_coreapps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn

      - name: Build web
        run: yarn build
        env: 
          CI: false
          
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: Upload new web-build
        run: |
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }} --delete
